routes:
  /:
    controller: page
    filter: slug:home
    template: page

collections:
  /media/:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
