## Trigger workflow: test comment
routes:
  /:
    data: page.home
    template: home

collections:
  /media/:
    permalink: /media/{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
